export enum ApiCodeResponse {
  TEST = 'api.result.test',
  NO_TOKEN_FOUNDED = 'api.security.token.no_token_founded',
  TOKEN_EXPIRED = 'api.security.token.token_expired',
  TOKEN_GEN_ERROR = 'api.security.token.token_gen_error',
  SIGNUP_ERROR = 'api.security.user.signup_error',
  SIGNIN_ERROR = 'api.security.user.signin_error',
  GOOGLE_AUTH_ERROR = 'api.security.user.google-auth-error',
  FACEBOOK_AUTH_ERROR = 'api.security.user.facebook-auth-error',
  SOCIAL_SIGN_ERROR = 'api.security.user.social-sign-error',
  USER_NOT_FOUND = 'api.security.user.user_not_found',
  CREDENTIAL_DELETE_ERROR = 'api.security.user.credential_delete_error',
  USER_ALREADY_EXIST = 'api.security.user.user_already_exist',
  PAYLOAD_IS_NOT_VALID = 'api.error.payload-is-not-valid',
  PAYLOAD_PARAM_IS_MISSING = 'api.error.payload-params-missing',
  COMMON_SUCCESS = 'api.result.common-succes',
  USERNAME_IS_NOT_EMPTY = 'api.error.username-is-empty',
  USERNAME_IS_LENGTH = 'api.error.username-length',
  PASSWORD_IS_NOT_EMPTY = 'api.error.password-is-empty',
  PASSWORD_IS_LENGTH = 'api.error.password-length',
  MAIL_IS_EMAIL = 'api.error.mail-is-invalid',
  MAIL_IS_NOT_EMPTY = 'api.error.mail-is-empty',
  USERNAME_MATCHES = 'api.error.username-is-invalid',
  PASSWORD_MATCHES = 'api.error.password-is-invalid',
  MAIL_MATCHES = 'api.error.mail-is-invalid',
  GOOGLEHASH_MATCHES = 'api.error.google-hash-is-invalid',
  FACEBOOKHASH_MATCHES = 'api.error.facebook-hash-is-invalid',

  //Member
  MEMBER_PAYLOAD_MEMBER_ID_MANDATORY ='api.member.error.id-mandatory',
  MEMBER_PAYLOAD_MEMBER_ID_LENGTH_ERROR ='api.member.error.id-lenght',
  MEMBER_PAYLOAD_FIRSTNAME_IS_NOT_STRING ='api.member.error.firstname-is-not-string',
  MEMBER_PAYLOAD_FIRSTNAME_LENGTH_ERROR='api.member.error.firstname-length',
  MEMBER_PAYLOAD_LASTNAME_IS_NOT_STRING='api.member.error.lastname-is-not-string',
  MEMBER_PAYLOAD_LASTNAME_LENGTH_ERROR='api.member.error.lastname-length',
  MEMBER_PAYLOAD_BIRTHDATE_IS_NOT_VALID='api.member.error.birthdate-invalid',
  MEMBER_PAYLOAD_GENDER_IS_NOT_VALID='api.member.error.gender-invalid',
  MEMBER_PAYLOAD_MAIL_IS_NOT_VALID='api.member.error.mail-invalid',
  MEMBER_PAYLOAD_MAIL_LENGTH_ERROR='api.member.error.mail-length',
  MEMBER_PAYLOAD_PHONE_LENGTH_ERROR='api.member.error.phone-length',
  MEMBER_PAYLOAD_IBAN_LENGTH_ERROR='api.member.error.iban-length',
  MEMBER_PAYLOAD_ACTIVATION_CODE_LENGTH_ERROR='api.member.error.activation-code-length',
  MEMBER_PAYLOAD_SUBSCRIPTION_NOT_VALID='api.member.error.payload-subscription-invalid',
  MEMBER_PAYLOAD_ACTIVE_INVALID='api.member.error.payload-active-invalid'

}
